apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-demo-scaledobject
  namespace: default
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    apiVersion: apps/v1
    name: keda-demo
    kind: Deployment
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:9090
      query: sum(irate(http_request_duration_seconds_count{app="keda-demo"}[1m]))
      threshold: '10'
