apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-demo
  name: keda-demo
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30443
  selector:
    app: keda-demo
  type: NodePort
